[maistra-2.6] Rebase commits between 2.5.0 and 2.5.2
Maistra/istio pull request #1016
Opened 2024-06-03 12:26 UTC by yannuil

2024-06-04 11:12 UTC, yannuil commented
/retest

2024-06-04 12:02 UTC, jewertow requested changes, later dismissed
OSSM-5556 was reverted: https://github.com/maistra/istio/pull/964

2024-06-04 12:16 UTC, yannuil commented
@jewertow as you suggest in the reverted commit, we don't want to include the fix in the Z-stream. This is a Y-stream. Should we include it?

2024-06-04 12:48 UTC, yannuil commented
/retest

2024-06-04 13:04 UTC, jewertow commented
No, we do not want that change at all.

2024-06-05 08:57 UTC, yannuil commented
I have dropped a [commit](https://github.com/maistra/istio/commit/bd3d6530e48034b35236392de447a86d852013b1) to resolve the conflict with #1002. The commit was picked from istio/istio#48056, which includes some changes on [`pilot/pkg/config/kube/gateway/conditions.go`](https://github.com/istio/istio/pull/48056/files#diff-62af8b3a3ade7a9e214848a880e4a3d588214d5ccbfc7ff2ee0c477f467c18dc). Do we need to incorporate them as well? @jewertow @eoinfennessy

2024-06-05 09:16 UTC, eoinfennessy commented
> I have dropped a [commit](https://github.com/maistra/istio/commit/bd3d6530e48034b35236392de447a86d852013b1) to resolve the conflict with #1002. The commit was picked from [istio/istio#48056](https://github.com/istio/istio/pull/48056), which includes some changes on [`pilot/pkg/config/kube/gateway/conditions.go`](https://github.com/istio/istio/pull/48056/files#diff-62af8b3a3ade7a9e214848a880e4a3d588214d5ccbfc7ff2ee0c477f467c18dc). Do we need to incorporate them as well?

Yes, I think we should incorporate the changes in `conditions.go`. You may be able to use the `controllerName` variable defined in `model.go`.

2024-06-06 10:53 UTC, yannuil commented
/retest-required

2024-06-06 11:41 UTC, eoinfennessy commented on pilot/pkg/config/kube/gateway/controller_test.go
> +		ControllerName: k8sv1.GatewayController(features.ManagedGatewayController),
For consistency, should we use `controllerName` here?

2024-06-06 11:42 UTC, eoinfennessy commented on pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
> +			ControllerName: k8sv1.GatewayController(features.ManagedGatewayController),
> For consistency, should we use `controllerName` here?

...and here also?

2024-06-06 15:47 UTC, yannuil commented
/test maistra-istio-unit-2-6

2024-06-06 22:34 UTC, eoinfennessy commented
/test maistra-istio-unit-2-6

2024-06-07 10:38 UTC, yannuil commented
/test maistra-istio-unit-2-6

2024-06-07 18:06 UTC, yannuil commented
/test maistra-istio-unit-2-6

2024-06-08 08:28 UTC, yannuil commented
/test maistra-istio-unit-2-6

2024-06-10 09:08 UTC, yannuil commented
/test maistra-istio-unit-2-6

2024-06-10 09:08 UTC, yannuil commented
/retest-required

2024-06-10 10:01 UTC, eoinfennessy commented
Do we want `tide/merge-method-rebase` on this PR?

2024-06-10 12:02 UTC, eoinfennessy approved these changes

2024-06-11 10:13 UTC, jewertow commented
@eoinfennessy yes, we do.

2024-06-12 12:19 UTC, merged