MAISTRA-2153: Disable namespace informer if MemberRoll is used
Maistra/istio pull request #283
Opened 2021-03-02 12:55 UTC by bison

This causes istiod to skip creating the namespace informer in the
Kubernetes service registry controller if a MemberRoll is specified,
because Maistra cannot read namespace objects.  This will affect the
behavior of multi-network deployments that do not use mesh networks
for configuration, i.e. a namespace cannot be labeled with a default
network now.

2021-03-02 12:56 UTC, bison commented
This partially breaks the multi-network stuff. Does that affect our plans for federation or anything? cc: @dgn

2021-03-02 12:58 UTC, bison commented
I guess we could call this handler when the MemberRoll changes. Do we want to do that, or does this just not matter for us?

2021-03-02 15:07 UTC, rcernich commented
I wonder if a simple watch on the namespace is enough, as it appears it's only watching the `systemNamespace` anyway (I assume that's what the filter is doing).

2021-03-02 15:16 UTC, dgn commented
afaik we can't even watch our own namespace

2021-03-02 15:16 UTC, dgn commented
we're not really using the multi-network stuff at this point, and the labelling is also not strictly required for multi-cluster/federation

2021-03-02 15:55 UTC, bison commented
> I wonder if a simple watch on the namespace is enough, as it appears it's only watching the systemNamespace anyway (I assume that's what the filter is doing).

Ah, true. So no need to connect this to MemberRoll then, but like Daniel said, I don't think we can watch namespaces at all. So I guess Maistra just can't support this.

2021-03-03 13:32 UTC, dgn approved these changes

2021-03-03 13:39 UTC, dgn requested changes
looking through the code, this isn't the only place namespaces are watched. there's a namespace controller in `pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go` that is initialized in `pilot/pkg/bootstrap/server.go:1093`

2021-03-03 14:09 UTC, bison commented
We handle that in the namespace controller by using the MemberRoll instead.

2021-03-03 14:11 UTC, bison commented
There's also a separate issue I'm working on for a list of namespaces that happens elsewhere: [MAISTRA-2152](https://issues.redhat.com/browse/MAISTRA-2152)

2021-03-03 15:53 UTC, dgn approved these changes
That's right, sorry I was looking at the wrong branch here

2021-03-04 10:56 UTC, merged