[maistra-1.1-future] Pilot
Maistra/istio pull request #67
Opened 2019-12-19 13:11 UTC by dgn

NOTE: https://github.com/Maistra/istio/pull/66 should be merged before reviewing this one, as it contains the same commits.

This covers all Maistra-specific changes that went into Pilot. I started out trying to re-arrange commits (e.g. separating out the PodLocality work), but because then the following commits wouldn't apply anymore, I just left the order as-is. The only changes I made are about what parts were touched: this PR really only contains Pilot changes.

2020-01-03 17:39 UTC, brian-avery approved these changes

2020-01-07 19:33 UTC, rcernich approved these changes

2020-01-07 19:44 UTC, rcernich requested changes
The code changes look fine, but I think you need to update [clusterrole.yaml](https://github.com/Maistra/istio/blob/maistra-1.1-future/install/kubernetes/helm/istio/charts/pilot/templates/clusterrole.yaml) file to include permissions to get/list/watch SMMR, authentication.maistra.io, and rbac.maistra.io resources.

2020-01-08 08:49 UTC, dgn commented
Hey Rob, the permissions for `authentication.maistra.io` and `rbac.maistra.io` will be part of the upcoming PR that re-introduces those CRs. The SMMR permissions are being patched in by the operator scripts: https://github.com/Maistra/istio-operator/blob/6fee5c2ad170d5532976805ffc57bbc73ca9640a/tmp/build/patch-charts.sh#L232

2020-01-08 15:58 UTC, rcernich approved these changes

2020-01-08 16:05 UTC, merged