[maistra-1.1-future] Citadel
Maistra/istio pull request #70
Opened 2019-12-20 09:35 UTC by dgn

NOTE: this PR is based on the changes in #66, so that should be merged before reviewing this one.

2020-01-03 15:38 UTC, brian-avery approved these changes

2020-01-07 19:54 UTC, rcernich requested changes
The code changes look fine, but I think you need to update [clusterrole.yaml](https://github.com/Maistra/istio/blob/maistra-1.1-future/install/kubernetes/helm/istio/charts/security/templates/clusterrole.yaml) file to include permissions to get/list/watch SMMR resources.

2020-01-08 08:52 UTC, dgn commented
Hey Rob, the permissions for authentication.maistra.io and rbac.maistra.io will be part of the upcoming PR that re-introduces those CRs. The SMMR permissions are being patched in by the operator scripts: https://github.com/Maistra/istio-operator/blob/6fee5c2ad170d5532976805ffc57bbc73ca9640a/tmp/build/patch-charts.sh#L232

2020-01-08 15:57 UTC, rcernich approved these changes

2020-01-08 16:02 UTC, merged